name: pokedex
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.1.6
  cupertino_icons: ^1.0.2
  
  csv: ^5.0.0
  stack: ^0.2.1 
  path: ^1.8.0
  sqflite: ^2.0.2+1
  
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  http: ^0.13.4
  url_launcher: ^6.1.0

  sliding_up_panel: ^2.0.0+1
  expandable: ^5.0.1
  cached_network_image: ^3.2.0
  graphview: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  bloc_test: ^9.0.0
  mocktail: ^0.2.0

flutter_native_splash:
  background_image: "assets/pokeball_theme_background_full_radius.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon900.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/normal/
    - assets/types/
  
  fonts:
    - family: Pokemon Solid
      fonts:
        - asset: assets/fonts/Pokemon Solid.ttf
    - family: Pokemon Hollow
      fonts:
        - asset: assets/fonts/Pokemon Hollow.ttf
    - family: Merchant Copy
      fonts:
        - asset: assets/fonts/Merchant Copy.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
